version: "3.2"

services:
  api:
    restart: always
    networks:
      - vegadns_net
    build: .
    image: vegadns/api:${API_TAG}
    ports:
      - target: "5000"
        protocol: "tcp"
    # volumes:
    #   - ${PWD}/vegadns:/opt/vegadns/vegadns # Helpful for debugging
    environment:
      # WORKERS: 2 # Helpful for debugging quick restarts of gunicorn
      DB_HOST: mysql
      DB_USER: vegadns
      SECRET_DB_PASS: secret
      TRUSTED_IPS: 0.0.0.0/0
      API_PORT: 5000
      ENABLE_CONSUL_NOTIFICATIONS: "true"
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
      CONSUL_KEY: ${CONSUL_KEY}
      CONSUL_LOCK_KEY: ${CONSUL_LOCK_KEY}
      SECRET_COOKIE_SECRET: ${SECRET_COOKIE_SECRET}
    depends_on:
      - mysql
      - consul
  ui:
    restart: always
    networks:
      - vegadns_net
    image: vegadns/ui
    ports:
      - target: "80"
        protocol: "tcp"
    depends_on:
      - api
    environment:
      # don't set this to api:5000 unless "api" resolves on your local machine
      # all client API requests are done from the browser!
      API_URL: ${API_URL}
